// Code generated by "core generate -add-types"; DO NOT EDIT.

package skca_plot

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/chans/skca_plot.Plot", IDName: "plot", Doc: "Plot holds the params, table, etc", Methods: []types.Method{{Name: "GCaRun", Doc: "GCaRun plots the conductance G (and other variables) as a function of Ca.", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}, {Name: "TimeRun", Doc: "TimeRun runs the equation over time.", Directives: []types.Directive{{Tool: "types", Directive: "add"}}}}, Fields: []types.Field{{Name: "SKCa", Doc: "SKCa params"}, {Name: "CaParams", Doc: "time constants for integrating Ca from spiking across M, P and D cascading levels"}, {Name: "NoSpikeThr", Doc: "threshold of SK M gating factor above which the neuron cannot spike"}, {Name: "CaStep", Doc: "Ca conc increment for M gating func plot"}, {Name: "TimeSteps", Doc: "number of time steps"}, {Name: "TimeSpike", Doc: "do spiking instead of Ca conc ramp"}, {Name: "SpikeFreq", Doc: "spiking frequency"}, {Name: "Dir"}, {Name: "Tabs"}}})
