Name = 'RA25x'
Title = 'Axon random associator: experimental version'
URL = 'https://github.com/emer/axon/blob/main/sims/ra25x/README.md'
Doc = 'This demonstrates a basic Axon model and provides a template for creating new models. It has a random-associator four-layer axon network that uses the standard supervised learning paradigm to learn mappings between 25 random input / output patterns defined over 5x5 input / output layers.'
Includes = []
GUI = false
Debug = false
GPU = true

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

  [Params.Hidden1Size]
    X = 10
    Y = 10

  [Params.Hidden2Size]
    X = 10
    Y = 10

[Run]
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 1000
  Trials = 32
  Cycles = 200
  PlusCycles = 50
  NZero = 0
  TestInterval = 5
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Expt',
    'Run',
    'Epoch'
  ]
  Test = []
