Includes = []
GUI = false
Debug = false

[Mod]
  InToEc2PCon = 0.25
  ECPctAct = 0.2
  MemThr = 0.34

[Hip]
  DGRatio = 2.236
  EC3ToEC2PCon = 0.1
  EC2ToDGPCon = 0.25
  EC2ToCA3PCon = 0.25
  CA3ToCA1PCon = 0.25
  DGToCA3PCon = 0.02
  EC2LatRadius = 2
  EC2LatSigma = 2.0
  MossyDelta = 1.0
  MossyDeltaTest = 0.75
  ThetaLow = 0.9
  ThetaHigh = 1.0
  EC5Clamp = true
  EC5ClampSrc = 'EC3'
  EC5ClampTest = false
  EC5ClampThr = 0.1

  [Hip.EC2Size]
    X = 21
    Y = 21

  [Hip.EC3NPool]
    X = 2
    Y = 3

  [Hip.EC3NNrn]
    X = 7
    Y = 7

  [Hip.CA1NNrn]
    X = 10
    Y = 10

  [Hip.CA3Size]
    X = 20
    Y = 20

[Pat]
  MinDiffPct = 0.5
  DriftCtxt = false
  CtxtFlipPct = 0.25
  DriftPct = 0.0

[Params]
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  StopMem = 0.9
  GPU = true
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 100
  NTrials = 20
  NData = 10
  TestInterval = 1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
