Name = 'Hip'
Title = 'Axon hippocampus'
URL = 'https'
Doc = 'Simulates the hippocampus on basic AB-AC paired associates task.'
Includes = [
  'medhip.toml'
]
GUI = false
Debug = false

[Hip]
  DGRatio = 2.236
  EC3ToEC2PCon = 0.1
  EC2ToDGPCon = 0.25
  EC2ToCA3PCon = 0.25
  CA3ToCA1PCon = 0.25
  DGToCA3PCon = 0.02
  EC2LatRadius = 2
  EC2LatSigma = 2.0
  MossyDelta = 1.0
  MossyDeltaTest = 0.75
  ThetaLow = 0.9
  ThetaHigh = 1.0
  EC5Clamp = true
  EC5ClampSrc = 'EC3'
  EC5ClampTest = true
  EC5ClampThr = 0.1

  [Hip.EC2Size]
    X = 21
    Y = 21

  [Hip.EC3NPool]
    X = 2
    Y = 3

  [Hip.EC3NNrn]
    X = 7
    Y = 7

  [Hip.CA1NNrn]
    X = 15
    Y = 15

  [Hip.CA3Size]
    X = 30
    Y = 30

[Env]
  ECPctAct = 0.2
  MinDiffPct = 0.5
  DriftCtxt = false
  CtxtFlipPct = 0.25
  DriftPct = 0.1

[Params]
  InToEc2PCon = 0.25
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 10
  NThreads = 0
  MemThr = 0.34
  StopMem = 0.9
  Run = 0
  Runs = 5
  Epochs = 100
  Trials = 10
  Cycles = 200
  PlusCycles = 50
  TestInterval = 5

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
