[[Base]]
  Sel = ".InhibLateral"
  Desc = "circle lateral inhibitory connection -- good params, longer time, more ABmem"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Abs" = "0.1"
    "Path.SWts.Init.Sym" = "false"
    "Path.SWts.Init.Var" = "0"

[[Base]]
  Sel = ".HippoCHL"
  Desc = "hippo CHL pathways -- no norm, moment, but YES wtbal = sig better"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.2"
    "Path.Learn.Learn" = "true"

[[Base]]
  Sel = ".PPath"
  Desc = "performant path, new Dg error-driven EcCa1Path paths"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.2"
    "Path.Learn.Learn" = "true"

[[Base]]
  Sel = "#CA1ToEC5"
  Desc = "extra strong from CA1 to EC5"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.4"
    "Path.PathScale.Abs" = "3.0"

[[Base]]
  Sel = "#InputToEC2"
  Desc = "for CAN ec2"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Rel" = "2.0"

[[Base]]
  Sel = "#InputToEC3"
  Desc = "one-to-one input to EC"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.SWts.Init.Mean" = "0.8"
    "Path.SWts.Init.Var" = "0.0"

[[Base]]
  Sel = "#EC3ToEC2"
  Desc = "copied from InputToEC2"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Abs" = "0.5"

[[Base]]
  Sel = "#EC5ToEC3"
  Desc = "one-to-one out to in"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Rel" = "0.5"
    "Path.SWts.Init.Mean" = "0.9"
    "Path.SWts.Init.Var" = "0.01"

[[Base]]
  Sel = "#DGToCA3"
  Desc = "Mossy fibers: strong, non-learning"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Abs" = "0.3"
    "Path.PathScale.Rel" = "4"
    "Path.SWts.Init.Var" = "0.01"

[[Base]]
  Sel = "#CA3ToCA3"
  Desc = "CA3 recurrent cons: rel=2 still the best"
  [Base.Params]
    "Path.PathScale.Abs" = "0.3"
    "Path.PathScale.Rel" = "2"

[[Base]]
  Sel = "#EC2ToDG"
  Desc = "DG learning is surprisingly critical: maxed out fast, hebbian works best"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.2"
    "Path.Learn.Learn" = "true"
    "Path.PathScale.Abs" = "0.7"

[[Base]]
  Sel = "#CA3ToCA1"
  Desc = "Schaffer collaterals -- slower, less hebb"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.2"

[[Base]]
  Sel = "#EC5ToCA1"
  Desc = "EC5 Perforant Path"
  [Base.Params]
    "Path.PathScale.Rel" = "0.3"

[[Base]]
  Sel = ".EC"
  Desc = "all EC layers: only pools, no layer-level -- now for EC3 and EC5"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.4"
    "Layer.Inhib.ActAvg.Nominal" = "0.05"
    "Layer.Inhib.Layer.On" = "false"
    "Layer.Inhib.Pool.Gi" = "1.1"
    "Layer.Inhib.Pool.On" = "true"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = "#DG"
  Desc = "very sparse = high inhibition"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.01"
    "Layer.Inhib.Layer.Gi" = "2.4"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = "#EC2"
  Desc = "very sparse = high inhibition"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.02"
    "Layer.Inhib.Layer.Gi" = "1.2"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = "#CA3"
  Desc = "sparse = high inhibition"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.01"
    "Layer.Inhib.Layer.Gi" = "1.2"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = "#CA1"
  Desc = "CA1 only Pools"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.03"
    "Layer.Inhib.Layer.On" = "false"
    "Layer.Inhib.Pool.Gi" = "1.1"
    "Layer.Inhib.Pool.On" = "true"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"
