Name = 'PCoreVS'
Title = 'Pallidal Core (GPe) Ventral Striatum'
URL = 'https://github.com/emer/axon/blob/main/sims/bgventral/README.md'
Doc = 'This project simulates the Ventral Basal Ganglia, starting with the Ventral Striatum, centered on the Pallidum Core (GPe) areas that drive Go vs. No engagement in a goal.'
Includes = []
GUI = false
Debug = false
GPU = true

[Env]
  ZeroTest = false

[Params]
  Tweak = false
  Baseline = false
  DryRun = false
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 1
  Epochs = 30
  Trials = 128
  Cycles = 200
  PlusCycles = 50

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
