Name = 'VSPatch'
Title = 'Ventral Striatum Patch'
URL = 'https'
Doc = 'This project simulates the Ventral Striatum (VS) Patch (striosome) neurons that predict reward to generate an RPE (reward prediction error). It is a testbed for learning the quantitative value representations needed for this.'
Includes = []
GUI = false
Debug = false

[Env]

[Params]
  Tweak = false
  Baseline = false
  DryRun = false
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 1
  CondEpochs = 20
  Epochs = 100
  Trials = 256
  Cycles = 200
  PlusCycles = 50

[Log]
  AggStats = [
    'Rew',
    'RewPred',
    'DA',
    'RewPred_NR',
    'DA_NR'
  ]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
