Includes = []
GUI = false
Debug = false

[Env]

[Params]
  Tweak = false
  Baseline = false
  DryRun = false
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 1
  CondEpochs = 20
  NEpochs = 100
  NTrials = 256

[Log]
  AggStats = [
    'Rew',
    'RewPred',
    'DA',
    'RewPred_NR',
    'DA_NR'
  ]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
  Testing = false
