[[Base]]
  Sel = "Layer"
  Desc = "clamp gain makes big diff on overall excitation, gating propensity"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.0"

[[Base]]
  Sel = "#State"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.2"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "0.5"
    "Layer.Inhib.Layer.On" = "true"
    "Layer.Inhib.Pool.On" = "false"
    "Layer.Learn.NeuroMod.AChLRateMod" = "0"
    "Layer.Learn.NeuroMod.DAModGain" = "0"
    "Layer.Learn.NeuroMod.DipGain" = "1"
    "Layer.Learn.RLRate.SigmoidMin" = "1"
    "Layer.Learn.TrgAvgAct.GiBaseInit" = "0"

[[Base]]
  Sel = ".VSPatchPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.02"
    "Path.Learn.Trace.LearnThr" = "0"
    "Path.PathScale.Abs" = "2"
    "Path.SWts.Init.Mean" = "0.5"
    "Path.SWts.Init.Var" = "0.25"
