Name = 'DeepMove'
Title = 'DeepAxon Move Prediction'
URL = 'https://github.com/emer/axon/blob/main/sims/deepmove/README.md'
Doc = 'This demonstrates a basic deep predictive learning Axon model that learns to predict the effects of movement on visual inputs.'
Includes = []
GUI = false
Debug = false
GPU = true

[Env]
  UnitsPer = 4

  [Env.Env]
    PctBlank = 0.0

[Params]
  Hid2 = false
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 2
  Epochs = 100
  Trials = 196
  Cycles = 200
  PlusCycles = 50
  TestInterval = 0
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Expt',
    'Run',
    'Epoch'
  ]
  Test = []
