Includes = []
GUI = true
Debug = false
OpenWts = ''

[Env]
  Config = '01_us_magnitude.toml'
  NDrives = 4
  PctCortexStEpc = 50
  PctCortexNEpc = 1
  PctCortex = 0.0
  SameSeed = false

[Params]
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = false
  NData = 1
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 50
  NTrials = 128
  NCycles = 300
  PCAInterval = 10

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  NetData = false
  Testing = false
