Name = 'Choose'
Title = 'Choose Maze Arms'
URL = 'https'
Doc = 'This project tests the Rubicon framework making cost-benefit based choices.'
Includes = []
GUI = false
Debug = false

[Env]
  Config = '02_us_probability.toml'
  NDrives = 4
  PctCortexStEpc = 50
  PctCortexNEpc = 1
  PctCortex = 0.0
  SameSeed = false

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 8
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 100
  Trials = 128
  Cycles = 200
  PlusCycles = 50
  PCAInterval = 10

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
