// Code generated by "core generate -add-types -add-funcs -setters -gosl"; DO NOT EDIT.

package emery

import (
	"cogentcore.org/core/enums"
)

var _ActionsValues = []Actions{0, 1}

// ActionsN is the highest valid value for type Actions, plus one.
//
//gosl:start
const ActionsN Actions = 2

//gosl:end

var _ActionsValueMap = map[string]Actions{`Rotate`: 0, `Forward`: 1}

var _ActionsDescMap = map[Actions]string{0: `Rotate is overall body rotation. Positive or negative for left vs. right.`, 1: `Forward moving forward or backward.`}

var _ActionsMap = map[Actions]string{0: `Rotate`, 1: `Forward`}

// String returns the string representation of this Actions value.
func (i Actions) String() string { return enums.String(i, _ActionsMap) }

// SetString sets the Actions value from its string representation,
// and returns an error if the string is invalid.
func (i *Actions) SetString(s string) error {
	return enums.SetString(i, s, _ActionsValueMap, "Actions")
}

// Int64 returns the Actions value as an int64.
func (i Actions) Int64() int64 { return int64(i) }

// SetInt64 sets the Actions value from an int64.
func (i *Actions) SetInt64(in int64) { *i = Actions(in) }

// Desc returns the description of the Actions value.
func (i Actions) Desc() string { return enums.Desc(i, _ActionsDescMap) }

// ActionsValues returns all possible values for the type Actions.
func ActionsValues() []Actions { return _ActionsValues }

// Values returns all possible values for the type Actions.
func (i Actions) Values() []enums.Enum { return enums.Values(_ActionsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Actions) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Actions) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "Actions") }

var _EmeryBodiesValues = []EmeryBodies{0, 1, 2, 3}

// EmeryBodiesN is the highest valid value for type EmeryBodies, plus one.
//
//gosl:start
const EmeryBodiesN EmeryBodies = 4

//gosl:end

var _EmeryBodiesValueMap = map[string]EmeryBodies{`EmeryBody`: 0, `EmeryHead`: 1, `EmeryEyeL`: 2, `EmeryEyeR`: 3}

var _EmeryBodiesDescMap = map[EmeryBodies]string{0: ``, 1: ``, 2: ``, 3: ``}

var _EmeryBodiesMap = map[EmeryBodies]string{0: `EmeryBody`, 1: `EmeryHead`, 2: `EmeryEyeL`, 3: `EmeryEyeR`}

// String returns the string representation of this EmeryBodies value.
func (i EmeryBodies) String() string { return enums.String(i, _EmeryBodiesMap) }

// SetString sets the EmeryBodies value from its string representation,
// and returns an error if the string is invalid.
func (i *EmeryBodies) SetString(s string) error {
	return enums.SetString(i, s, _EmeryBodiesValueMap, "EmeryBodies")
}

// Int64 returns the EmeryBodies value as an int64.
func (i EmeryBodies) Int64() int64 { return int64(i) }

// SetInt64 sets the EmeryBodies value from an int64.
func (i *EmeryBodies) SetInt64(in int64) { *i = EmeryBodies(in) }

// Desc returns the description of the EmeryBodies value.
func (i EmeryBodies) Desc() string { return enums.Desc(i, _EmeryBodiesDescMap) }

// EmeryBodiesValues returns all possible values for the type EmeryBodies.
func EmeryBodiesValues() []EmeryBodies { return _EmeryBodiesValues }

// Values returns all possible values for the type EmeryBodies.
func (i EmeryBodies) Values() []enums.Enum { return enums.Values(_EmeryBodiesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i EmeryBodies) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *EmeryBodies) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "EmeryBodies")
}

var _SensesValues = []Senses{0, 1, 2, 3, 4, 5}

// SensesN is the highest valid value for type Senses, plus one.
//
//gosl:start
const SensesN Senses = 6

//gosl:end

var _SensesValueMap = map[string]Senses{`VSRotHVel`: 0, `VMRotHVel`: 1, `VSRotHDir`: 2, `VSRotHAccel`: 3, `VSLinearVel`: 4, `VSLinearAccel`: 5}

var _SensesDescMap = map[Senses]string{0: `VSRotHVel is vestibular rotational head velocity (horiz plane).`, 1: `VMRotHVel is full-field visual-motion rotation (horiz plane).`, 2: `VSRotHDir is the ground-truth actual head direction (horiz plane).`, 3: `VSRotHAccel is vestibular rotational head acceleration (horiz plane).`, 4: `VSLinearVel is vestibular linear velocity. This is not actually something that can be sensed directly by the vestibular system: only linear accel.`, 5: `VSLinearAccel is vestibular linear acceleration.`}

var _SensesMap = map[Senses]string{0: `VSRotHVel`, 1: `VMRotHVel`, 2: `VSRotHDir`, 3: `VSRotHAccel`, 4: `VSLinearVel`, 5: `VSLinearAccel`}

// String returns the string representation of this Senses value.
func (i Senses) String() string { return enums.String(i, _SensesMap) }

// SetString sets the Senses value from its string representation,
// and returns an error if the string is invalid.
func (i *Senses) SetString(s string) error { return enums.SetString(i, s, _SensesValueMap, "Senses") }

// Int64 returns the Senses value as an int64.
func (i Senses) Int64() int64 { return int64(i) }

// SetInt64 sets the Senses value from an int64.
func (i *Senses) SetInt64(in int64) { *i = Senses(in) }

// Desc returns the description of the Senses value.
func (i Senses) Desc() string { return enums.Desc(i, _SensesDescMap) }

// SensesValues returns all possible values for the type Senses.
func SensesValues() []Senses { return _SensesValues }

// Values returns all possible values for the type Senses.
func (i Senses) Values() []enums.Enum { return enums.Values(_SensesValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Senses) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Senses) UnmarshalText(text []byte) error { return enums.UnmarshalText(i, text, "Senses") }
