// Code generated by "core generate -add-types -add-funcs -setters -gosl"; DO NOT EDIT.

package emery

import (
	"image"

	"cogentcore.org/core/core"
	"cogentcore.org/core/types"
	"cogentcore.org/core/xyz/xyzcore"
	"cogentcore.org/lab/base/randx"
	"cogentcore.org/lab/tensor"
	"github.com/emer/emergent/v2/popcode"
	"github.com/emer/v1vision/v1std"
)

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.Actions", IDName: "actions", Doc: "Actions are motor actions as abstracted coordinated plans\nthat unfold over time, at a level above individual muscles."})

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.Action", IDName: "action", Doc: "Action represents an action state.", Fields: []types.Field{{Name: "Time", Doc: "Time is the timestamp (Cycles, ms) for this state."}, {Name: "Actions", Doc: "Actions has the bits of active actions."}, {Name: "Values", Doc: "Values are the action parameters for each action\n(e.g., rotation degrees)."}, {Name: "Durations", Doc: "Durations are the number of cycles for the actions (from start),\ncomputed from the Value and the type of action."}}})

// SetTime sets the [Action.Time]:
// Time is the timestamp (Cycles, ms) for this state.
func (t *Action) SetTime(v int) *Action { t.Time = v; return t }

// SetActions sets the [Action.Actions]:
// Actions has the bits of active actions.
func (t *Action) SetActions(v Actions) *Action { t.Actions = v; return t }

// SetValues sets the [Action.Values]:
// Values are the action parameters for each action
// (e.g., rotation degrees).
func (t *Action) SetValues(v ...float32) *Action { t.Values = v; return t }

// SetDurations sets the [Action.Durations]:
// Durations are the number of cycles for the actions (from start),
// computed from the Value and the type of action.
func (t *Action) SetDurations(v ...int) *Action { t.Durations = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.ActionBuffer", IDName: "action-buffer", Doc: "ActionBuffer is a ring buffer for actions.", Fields: []types.Field{{Name: "States", Doc: "States are the action states."}, {Name: "WriteIndex", Doc: "WriteIndex is the current write index where a new item will be\nwritten (within range of States). Add post-increments."}}})

// SetStates sets the [ActionBuffer.States]:
// States are the action states.
func (t *ActionBuffer) SetStates(v ...Action) *ActionBuffer { t.States = v; return t }

// SetWriteIndex sets the [ActionBuffer.WriteIndex]:
// WriteIndex is the current write index where a new item will be
// written (within range of States). Add post-increments.
func (t *ActionBuffer) SetWriteIndex(v int) *ActionBuffer { t.WriteIndex = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.EmeryEnv", IDName: "emery-env", Doc: "EmeryEnv is the emery rat environment.", Fields: []types.Field{{Name: "Name", Doc: "name of this environment: Train or Test"}, {Name: "LeftEye", Doc: "LeftEye determines whether to process left eye image or not."}, {Name: "AngleCode", Doc: "angle population code values, in normalized units"}, {Name: "LinearCode", Doc: "population code for linear values, -1..1, in normalized units"}, {Name: "Motion", Doc: "Visual motion processing"}, {Name: "MotionImage", Doc: "Image processing for Motion."}, {Name: "UnitsPer", Doc: "UnitsPer is the number of units per localist value."}, {Name: "LinearUnits", Doc: "LinearUnits is the number of units per linear value."}, {Name: "AngleUnits", Doc: "AngleUnits is the number of units per angle value."}, {Name: "Geom", Doc: "Geom is the world geometry."}, {Name: "Params", Doc: "Params are sensory and motor parameters."}, {Name: "EyeRImage", Doc: "captured images"}, {Name: "EyeLImage", Doc: "captured images"}, {Name: "CurrentTime", Doc: "CurrentTime is the current timestep in msec. Counts up every Step,\n1 per msec (cycle)."}, {Name: "ActionStarts", Doc: "ActionStarts are points when actions have started, via inputs from\nthe network."}, {Name: "Actions", Doc: "Actions are continuously-recorded action states (every cycle)."}, {Name: "Senses", Doc: "Senses are continuously-recorded sensory states (every cycle)."}, {Name: "CurStates", Doc: "CurStates is the current rendered state tensors."}, {Name: "NextStates", Doc: "NextStates is the next rendered state tensors -- updated from actions."}, {Name: "Rand", Doc: "Rand is the random number generator for the env.\nAll random calls must use this.\nSet seed here for weight initialization values."}, {Name: "RandSeed", Doc: "random seed"}}})

// SetName sets the [EmeryEnv.Name]:
// name of this environment: Train or Test
func (t *EmeryEnv) SetName(v string) *EmeryEnv { t.Name = v; return t }

// SetLeftEye sets the [EmeryEnv.LeftEye]:
// LeftEye determines whether to process left eye image or not.
func (t *EmeryEnv) SetLeftEye(v bool) *EmeryEnv { t.LeftEye = v; return t }

// SetAngleCode sets the [EmeryEnv.AngleCode]:
// angle population code values, in normalized units
func (t *EmeryEnv) SetAngleCode(v popcode.Ring) *EmeryEnv { t.AngleCode = v; return t }

// SetLinearCode sets the [EmeryEnv.LinearCode]:
// population code for linear values, -1..1, in normalized units
func (t *EmeryEnv) SetLinearCode(v popcode.OneD) *EmeryEnv { t.LinearCode = v; return t }

// SetMotion sets the [EmeryEnv.Motion]:
// Visual motion processing
func (t *EmeryEnv) SetMotion(v v1std.MotionDoG) *EmeryEnv { t.Motion = v; return t }

// SetMotionImage sets the [EmeryEnv.MotionImage]:
// Image processing for Motion.
func (t *EmeryEnv) SetMotionImage(v v1std.Image) *EmeryEnv { t.MotionImage = v; return t }

// SetUnitsPer sets the [EmeryEnv.UnitsPer]:
// UnitsPer is the number of units per localist value.
func (t *EmeryEnv) SetUnitsPer(v int) *EmeryEnv { t.UnitsPer = v; return t }

// SetLinearUnits sets the [EmeryEnv.LinearUnits]:
// LinearUnits is the number of units per linear value.
func (t *EmeryEnv) SetLinearUnits(v int) *EmeryEnv { t.LinearUnits = v; return t }

// SetAngleUnits sets the [EmeryEnv.AngleUnits]:
// AngleUnits is the number of units per angle value.
func (t *EmeryEnv) SetAngleUnits(v int) *EmeryEnv { t.AngleUnits = v; return t }

// SetGeom sets the [EmeryEnv.Geom]:
// Geom is the world geometry.
func (t *EmeryEnv) SetGeom(v Geom) *EmeryEnv { t.Geom = v; return t }

// SetParams sets the [EmeryEnv.Params]:
// Params are sensory and motor parameters.
func (t *EmeryEnv) SetParams(v SensoryMotorParams) *EmeryEnv { t.Params = v; return t }

// SetEyeRImage sets the [EmeryEnv.EyeRImage]:
// captured images
func (t *EmeryEnv) SetEyeRImage(v image.Image) *EmeryEnv { t.EyeRImage = v; return t }

// SetEyeLImage sets the [EmeryEnv.EyeLImage]:
// captured images
func (t *EmeryEnv) SetEyeLImage(v image.Image) *EmeryEnv { t.EyeLImage = v; return t }

// SetCurrentTime sets the [EmeryEnv.CurrentTime]:
// CurrentTime is the current timestep in msec. Counts up every Step,
// 1 per msec (cycle).
func (t *EmeryEnv) SetCurrentTime(v int) *EmeryEnv { t.CurrentTime = v; return t }

// SetActionStarts sets the [EmeryEnv.ActionStarts]:
// ActionStarts are points when actions have started, via inputs from
// the network.
func (t *EmeryEnv) SetActionStarts(v ActionBuffer) *EmeryEnv { t.ActionStarts = v; return t }

// SetActions sets the [EmeryEnv.Actions]:
// Actions are continuously-recorded action states (every cycle).
func (t *EmeryEnv) SetActions(v ActionBuffer) *EmeryEnv { t.Actions = v; return t }

// SetSenses sets the [EmeryEnv.Senses]:
// Senses are continuously-recorded sensory states (every cycle).
func (t *EmeryEnv) SetSenses(v SenseBuffer) *EmeryEnv { t.Senses = v; return t }

// SetCurStates sets the [EmeryEnv.CurStates]:
// CurStates is the current rendered state tensors.
func (t *EmeryEnv) SetCurStates(v map[string]*tensor.Float32) *EmeryEnv { t.CurStates = v; return t }

// SetNextStates sets the [EmeryEnv.NextStates]:
// NextStates is the next rendered state tensors -- updated from actions.
func (t *EmeryEnv) SetNextStates(v map[string]*tensor.Float32) *EmeryEnv { t.NextStates = v; return t }

// SetRand sets the [EmeryEnv.Rand]:
// Rand is the random number generator for the env.
// All random calls must use this.
// Set seed here for weight initialization values.
func (t *EmeryEnv) SetRand(v randx.SysRand) *EmeryEnv { t.Rand = v; return t }

// SetRandSeed sets the [EmeryEnv.RandSeed]:
// random seed
func (t *EmeryEnv) SetRandSeed(v int64) *EmeryEnv { t.RandSeed = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.GUI", IDName: "gui", Doc: "GUI provides a GUI view onto the EmeryEnv", Fields: []types.Field{{Name: "Env", Doc: "Env is the environment we're viewing"}, {Name: "SceneEditor", Doc: "3D visualization of the Scene"}, {Name: "EyeRImageDisp", Doc: "first-person right-eye full field view"}, {Name: "EyeLImageDisp", Doc: "first-person left-eye fovea view"}}})

// SetEnv sets the [GUI.Env]:
// Env is the environment we're viewing
func (t *GUI) SetEnv(v *EmeryEnv) *GUI { t.Env = v; return t }

// SetSceneEditor sets the [GUI.SceneEditor]:
// 3D visualization of the Scene
func (t *GUI) SetSceneEditor(v *xyzcore.SceneEditor) *GUI { t.SceneEditor = v; return t }

// SetEyeRImageDisp sets the [GUI.EyeRImageDisp]:
// first-person right-eye full field view
func (t *GUI) SetEyeRImageDisp(v *core.Image) *GUI { t.EyeRImageDisp = v; return t }

// SetEyeLImageDisp sets the [GUI.EyeLImageDisp]:
// first-person left-eye fovea view
func (t *GUI) SetEyeLImageDisp(v *core.Image) *GUI { t.EyeLImageDisp = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.Senses", IDName: "senses", Doc: "Senses are sensory inputs that unfold over time.\nCan also use to store abstracted sensory state."})

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.Sense", IDName: "sense", Doc: "Sense represents a sensory state.", Fields: []types.Field{{Name: "Time", Doc: "Time is the timestamp (Cycles, ms) for this state."}, {Name: "Senses", Doc: "Senses has the bits of active senses."}, {Name: "Values", Doc: "Values are the values for each sense."}}})

// SetTime sets the [Sense.Time]:
// Time is the timestamp (Cycles, ms) for this state.
func (t *Sense) SetTime(v int) *Sense { t.Time = v; return t }

// SetSenses sets the [Sense.Senses]:
// Senses has the bits of active senses.
func (t *Sense) SetSenses(v Senses) *Sense { t.Senses = v; return t }

// SetValues sets the [Sense.Values]:
// Values are the values for each sense.
func (t *Sense) SetValues(v ...float32) *Sense { t.Values = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.SenseBuffer", IDName: "sense-buffer", Doc: "SenseBuffer is a ring buffer for senses.", Fields: []types.Field{{Name: "States", Doc: "States are the action states."}, {Name: "WriteIndex", Doc: "WriteIndex is the current write index where a new item will be\nwritten (within range of States). Add post-increments."}}})

// SetStates sets the [SenseBuffer.States]:
// States are the action states.
func (t *SenseBuffer) SetStates(v ...Sense) *SenseBuffer { t.States = v; return t }

// SetWriteIndex sets the [SenseBuffer.WriteIndex]:
// WriteIndex is the current write index where a new item will be
// written (within range of States). Add post-increments.
func (t *SenseBuffer) SetWriteIndex(v int) *SenseBuffer { t.WriteIndex = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.SensoryDelays", IDName: "sensory-delays", Doc: "SensoryDelays are delays from motor actions for different sensory modalities.", Fields: []types.Field{{Name: "Vestibular"}, {Name: "Visual"}}})

// SetVestibular sets the [SensoryDelays.Vestibular]
func (t *SensoryDelays) SetVestibular(v float32) *SensoryDelays { t.Vestibular = v; return t }

// SetVisual sets the [SensoryDelays.Visual]
func (t *SensoryDelays) SetVisual(v float32) *SensoryDelays { t.Visual = v; return t }

var _ = types.AddType(&types.Type{Name: "github.com/emer/axon/v2/sims/deepspace/emery.SensoryMotorParams", IDName: "sensory-motor-params", Doc: "SensoryMotorParams are parameters for sensory and motor properties.", Fields: []types.Field{{Name: "MaxRotate", Doc: "MaxRotate is maximum rotation angle magnitude per action, in degrees."}, {Name: "Delays", Doc: "Delays are sensory delays"}}})

// SetMaxRotate sets the [SensoryMotorParams.MaxRotate]:
// MaxRotate is maximum rotation angle magnitude per action, in degrees.
func (t *SensoryMotorParams) SetMaxRotate(v float32) *SensoryMotorParams { t.MaxRotate = v; return t }

// SetDelays sets the [SensoryMotorParams.Delays]:
// Delays are sensory delays
func (t *SensoryMotorParams) SetDelays(v SensoryDelays) *SensoryMotorParams { t.Delays = v; return t }
