Name = 'PVLV'
Title = 'Primary Value, Learned Value'
URL = 'https://github.com/emer/axon/blob/main/sims/pvlv/README.md'
Doc = 'Simulates the primary value, learned value model of classical conditioning and phasic dopamine in the amygdala, ventral striatum and associated areas.'
Includes = []
GUI = false
Debug = false
GPU = true

[Env]
  RunName = 'PosAcq_A100'
  SetNBlocks = false
  NBlocks = 0

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPUDevice = 0
  NThreads = 0
  Run = 0
  Runs = 25
  Cycles = 200
  PlusCycles = 50

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Testing = false
