Name = 'PVLV'
Title = 'Primary Value'
URL = 'https'
Doc = 'Simulates the primary value'
Includes = []
GUI = false
Debug = false

[Env]
  RunName = 'PosAcq_A100'
  SetNBlocks = false
  NBlocks = 0

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = false
  GPUDevice = 0
  NThreads = 0
  Run = 0
  Runs = 25
  Cycles = 200
  PlusCycles = 50

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Testing = false
