Includes = []
GUI = false
Debug = false

[Env]
  RunName = 'PosAcq_A100B50'
  SetNBlocks = false
  NBlocks = 0

[Params]
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = false
  NThreads = 0
  ThetaCycles = 300
  Run = 0
  NRuns = 1

[Log]
  AggStats = [
    'DA',
    'RewPred'
  ]
  SaveWts = false
  Block = true
  Cond = true
  Trial = false
  NetData = false
