Name = 'Objrec'
Title = 'Object Recognition'
URL = 'https'
Doc = 'This simulation explores how a hierarchy of areas in the ventral stream of visual processing (up to inferotemporal (IT) cortex) can produce robust object recognition that is invariant to changes in position'
Includes = []
GUI = false
Debug = false

[Env]
  NOutPer = 5

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

  [Params.V1V4Path]
    Recip = false
    Wrap = true

    [Params.V1V4Path.Size]
      X = 4
      Y = 4

    [Params.V1V4Path.Skip]
      X = 2
      Y = 2

    [Params.V1V4Path.Start]
      X = -1
      Y = -1

    [Params.V1V4Path.GaussFull]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8

    [Params.V1V4Path.GaussInPool]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8

    [Params.V1V4Path.SigFull]
      On = false
      Gain = 0.05
      CtrMove = 0.5

    [Params.V1V4Path.SigInPool]
      On = false
      Gain = 0.05
      CtrMove = 0.5

    [Params.V1V4Path.TopoRange]
      Min = 0.8
      Max = 1.0

[Run]
  GPU = true
  GPUDevice = 0
  NData = 32
  SlowInterval = 200
  AdaptGiInterval = 200
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 200
  Trials = 128
  Cycles = 200
  PlusCycles = 50
  NZero = 2
  TestInterval = 5
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
