Includes = []
GUI = false
Debug = false

[Env]
  NOutPer = 5

[Params]
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

  [Params.V1V4Path]
    Recip = false
    Wrap = true

    [Params.V1V4Path.Size]
      X = 4
      Y = 4

    [Params.V1V4Path.Skip]
      X = 2
      Y = 2

    [Params.V1V4Path.Start]
      X = -1
      Y = -1

    [Params.V1V4Path.GaussFull]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8

    [Params.V1V4Path.GaussInPool]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8

    [Params.V1V4Path.SigFull]
      On = false
      Gain = 0.05
      CtrMove = 0.5

    [Params.V1V4Path.SigInPool]
      On = false
      Gain = 0.05
      CtrMove = 0.5

    [Params.V1V4Path.TopoRange]
      Min = 0.8
      Max = 1.0

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 1
  NEpochs = 200
  NTrials = 128
  PCAInterval = 5
  TestInterval = -1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
