Name = 'Neuron'
Title = 'Axon single neuron'
URL = 'https'
Doc = 'This simulation demonstrates the basic properties of neural spiking and rate-code activation'
GeClamp = true
SpikeHz = 50.0
Ge = 0.1
Gi = 0.1
ErevE = 0.0
ErevI = -70.0
Noise = 0.0
KNaAdapt = true
MahpGk = 0.05
NMDAGbar = 0.006
GABABGbar = 0.015
VGCCGbar = 0.02
AKGk = 0.1
Includes = []
GUI = false
Debug = false

[Params]
  Sheet = ''
  Script = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  Cycles = 200
  OnCycle = 10
  OffCycle = 160

[Log]
  Save = false
