Name = 'Neuron'
Title = 'Axon single neuron'
URL = 'https://github.com/emer/axon/blob/main/sims/neuron/README.md'
Doc = 'This simulation gives an in-depth view inside the processing within an individual neuron, including the various channels that shape its dynamics in important ways.'
Includes = []
GUI = false
Debug = false
GPU = true
GeClamp = true
SpikeHz = 50.0
VgccGe = 0.02
AKGk = 0.1

[Params]
  Sheet = ''
  Script = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  Cycles = 200
  OnCycle = 10
  OffCycle = 160

[Log]
  Save = false
