[[30Notes]]
  Sel = ".InLay"
  Desc = "input layers need more inhibition"
  [30Notes.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.05"

[[Base]]
  Sel = "Layer"
  Desc = "generic layer params"
  [Base.Params]
    "Layer.Acts.Decay.Act" = "0.0"
    "Layer.Acts.Decay.Glong" = "0.0"
    "Layer.Acts.Dend.SSGi" = "2"
    "Layer.Acts.GabaB.Gbar" = "0.015"
    "Layer.Acts.Gbar.L" = "0.2"
    "Layer.Acts.Mahp.Gbar" = "0.04"
    "Layer.Acts.NMDA.Gbar" = "0.006"
    "Layer.Acts.NMDA.MgC" = "1.4"
    "Layer.Acts.NMDA.Voff" = "0"
    "Layer.Acts.Sahp.CaTau" = "5"
    "Layer.Acts.Sahp.Gbar" = "0.1"
    "Layer.Acts.Sahp.Off" = "0.8"
    "Layer.Acts.Sahp.Slope" = "0.02"
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Inhib.Layer.Gi" = "0.9"
    "Layer.Learn.TrgAvgAct.SubMean" = "1"
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.005"

[[Base]]
  Sel = ".SuperLayer"
  Desc = "super layer params"
  [Base.Params]
    "Layer.Bursts.ThrAbs" = "0.1"
    "Layer.Bursts.ThrRel" = "0.1"
    "Layer.Inhib.ActAvg.Nominal" = "0.1"

[[Base]]
  Sel = ".InLay"
  Desc = "input layers need more inhibition"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"

[[Base]]
  Sel = ".CTLayer"
  Desc = "CT NMDA gbar factor is key"
  [Base.Params]
    "Layer.Acts.Decay.Act" = "0.0"
    "Layer.Acts.Decay.Glong" = "0.0"
    "Layer.Acts.Dend.SSGi" = "0"
    "Layer.Acts.GabaB.Gbar" = "0.015"
    "Layer.Acts.MaintNMDA.Gbar" = "0.007"
    "Layer.Acts.MaintNMDA.Tau" = "300"
    "Layer.Acts.NMDA.Gbar" = "0.007"
    "Layer.Acts.NMDA.Tau" = "300"
    "Layer.Acts.Noise.Ge" = "0.005"
    "Layer.Acts.Noise.Gi" = "0.005"
    "Layer.Acts.Noise.On" = "false"
    "Layer.CT.DecayTau" = "50"
    "Layer.CT.GeGain" = "1.0"
    "Layer.Inhib.ActAvg.Nominal" = "0.12"
    "Layer.Inhib.Layer.Gi" = "2.2"

[[Base]]
  Sel = ".PulvinarLayer"
  Desc = "Pulv = Pulvinar"
  [Base.Params]
    "Layer.Acts.Decay.Act" = "0.0"
    "Layer.Acts.Decay.Glong" = "0.0"
    "Layer.Inhib.Layer.Gi" = "1.0"
    "Layer.Learn.RLRate.SigmoidMin" = "1.0"
    "Layer.Pulv.DriveScale" = "0.1"
    "Layer.Pulv.FullDriveAct" = "0.6"

[[Base]]
  Sel = "Prjn"
  Desc = "std"
  [Base.Params]
    "Prjn.Com.PFail" = "0.0"
    "Prjn.Learn.LRate.Base" = "0.005"
    "Prjn.Learn.Trace.SubMean" = "0"
    "Prjn.Learn.Trace.Tau" = "2"
    "Prjn.SWts.Adapt.LRate" = "0.0001"
    "Prjn.SWts.Init.SPct" = "1.0"

[[Base]]
  Sel = ".BackPrjn"
  Desc = "top-down back-projections MUST have lower relative weight scale, otherwise network hallucinates"
  [Base.Params]
    "Prjn.PrjnScale.Rel" = "0.1"

[[Base]]
  Sel = ".CTCtxtPrjn"
  Desc = "all CT context prjns"
  [Base.Params]
    "Prjn.Com.PFail" = "0.0"
    "Prjn.Learn.LRate.Base" = "0.001"
    "Prjn.Learn.Trace.SubMean" = "0"
    "Prjn.Learn.Trace.Tau" = "4"

[[Base]]
  Sel = ".CTFmSuper"
  Desc = "1to1 > full"
  [Base.Params]
    "Prjn.Learn.Learn" = "true"
    "Prjn.SWts.Init.Mean" = "0.5"
    "Prjn.SWts.Init.Var" = "0.25"

[[Base]]
  Sel = ".FmPulv"
  Desc = "defaults to .Back but generally weaker is better"
  [Base.Params]
    "Prjn.PrjnScale.Rel" = "0.1"

[[Base]]
  Sel = ".CTSelfCtxt"
  Desc = ""
  [Base.Params]
    "Prjn.Com.PFail" = "0.0"
    "Prjn.PrjnScale.Rel" = "0.5"
    "Prjn.SWts.Init.Sym" = "true"

[[Base]]
  Sel = ".CTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.Com.GType" = "MaintG"
    "Prjn.PrjnScale.Abs" = "0.2"
    "Prjn.SWts.Init.Sym" = "true"

[[Base]]
  Sel = "#HiddenCTToInputP"
  Desc = "differential contributions"
  [Base.Params]
    "Prjn.PrjnScale.Rel" = "1.0"

[[FullSong]]
  Sel = ".InLay"
  Desc = "input layers need more inhibition"
  [FullSong.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"

[[Hid2]]
  Sel = "#Hidden2CT"
  Desc = "CT NMDA gbar factor is key"
  [Hid2.Params]
    "Layer.Acts.GabaB.Gbar" = "0.3"
    "Layer.Acts.NMDA.Gbar" = "0.3"
    "Layer.Acts.NMDA.Tau" = "300"
    "Layer.Acts.Sahp.CaTau" = "10"
    "Layer.Inhib.ActAvg.Nominal" = "0.12"

[[Hid2]]
  Sel = "#Hidden2CTToHiddenCT"
  Desc = "ct top-down"
  [Hid2.Params]
    "Prjn.PrjnScale.Rel" = "0.1"

[[Hid2]]
  Sel = "#HiddenToHidden2"
  Desc = "jack up fwd pathway"
  [Hid2.Params]
    "Prjn.PrjnScale.Abs" = "2.0"

[[Hid2]]
  Sel = "#Hidden2CTToInputP"
  Desc = "differential contributions"
  [Hid2.Params]
    "Prjn.PrjnScale.Abs" = "1.0"
