GUI = true
Debug = false

[Env]
  RunName = "PosAcq_A100B50"

[Params]
  Sheet = ""
  Tag = ""
  Note = ""
  File = ""
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NThreads = 2
  Run = 0
  NRuns = 1

[Log]
  AggStats = ["DA", "VSPatch"]
  SaveWts = false
  Block = true
  Cond = true
  Trial = false
  NetData = false
