[[Base]]
  Sel = ".InputLayer"
  Desc = ""
  [Base.Params]
    "Layer.Acts.Decay.Act" = "1.0"
    "Layer.Acts.Decay.Glong" = "1.0"

[[Base]]
  Sel = "#CS"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.05"

[[Base]]
  Sel = "#ContextIn"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Learn.NeuroMod.DipGain" = "0.01"
    "Layer.VSPatch.Gain" = "30"
    "Layer.VSPatch.ThrInit" = "0.4"
    "Layer.VSPatch.ThrLRate" = "0.001"
    "Layer.VSPatch.ThrNonRew" = "10"

[[Base]]
  Sel = "#BLAPosExtD2"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.8"
    "Layer.Inhib.Pool.Gi" = "1.0"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Acts.MaintNMDA.Gbar" = "0.007"
    "Layer.Acts.MaintNMDA.Tau" = "200"
    "Layer.Inhib.Layer.Gi" = "3.2"
    "Layer.Inhib.Pool.Gi" = "3.2"

[[Base]]
  Sel = "#ContextInToBLAPosExtD2"
  Desc = "specific to this project"
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.1"
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".MatrixPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Matrix.NoGateLRate" = "0.0"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4.0"

[[Base]]
  Sel = ".BLAExtPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.02"

[[Base]]
  Sel = ".GPiToBGThal"
  Desc = "inhibition from GPi to MD"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = ".PTpToBLAExt"
  Desc = "modulatory, drives extinction learning based on maintained goal rep"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"

[[Base]]
  Sel = "#BLAPosAcqD1ToOFCus"
  Desc = "strong, high variance"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = "fixed inhibitory"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.0"

[[Base]]
  Sel = ".VSPatchPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.05"
    "Prjn.Learn.Trace.LearnThr" = "0.3"
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = ".PTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".ToPTp"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
