[[Base]]
  Sel = "Layer"
  Desc = "clamp gain makes big diff on overall excitation, gating propensity"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.0"

[[Base]]
  Sel = ".VBG"
  Desc = "all ModACh"
  [Base.Params]
    "Layer.Acts.Dend.ModACh" = "true"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.25"
    "Layer.Inhib.Layer.Gi" = "0.5"
    "Layer.Inhib.Pool.On" = "false"
    "Layer.Learn.NeuroMod.BurstGain" = "0.1"
    "Layer.Learn.NeuroMod.DAModGain" = "0"
    "Layer.Learn.RLRate.Diff" = "false"
    "Layer.Learn.RLRate.On" = "true"
    "Layer.Learn.RLRate.SigmoidMin" = "0.01"
    "Layer.Learn.TrgAvgAct.RescaleOn" = "true"
    "Layer.Matrix.GateThr" = "0.05"
    "Layer.Matrix.IsVS" = "true"

[[Base]]
  Sel = ".VSTNLayer"
  Desc = "all VSTN"
  [Base.Params]
    "Layer.Acts.Init.GeBase" = "0.1"
    "Layer.Acts.SKCa.CaRDecayTau" = "80"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModACh" = "true"
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Acts.Kir.Gbar" = "0"

[[Base]]
  Sel = ".ACC"
  Desc = "manipulate noise to see about integration over time"
  [Base.Params]
    "Layer.Acts.Noise.Ge" = "0.1"
    "Layer.Acts.Noise.Gi" = "0.01"
    "Layer.Acts.Noise.On" = "false"

[[Base]]
  Sel = ".VSMatrixPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.01"
    "Path.Learn.Trace.LearnThr" = "0.1"
    "Path.Matrix.VSRewLearn" = "false"
    "Path.SWts.Adapt.On" = "false"
  [Base.Hypers]
    [Base.Hypers."Path.Learn.LRate.Base"]
      Tweak = "-"
    [Base.Hypers."Path.Learn.Trace.LearnThr"]
      Tweak = "-"

[[Base]]
  Sel = "#UrgencyToVMtxGo"
  Desc = "strong urgency factor"
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Abs" = "0"
    "Path.PathScale.Rel" = "0.1"

[[Base]]
  Sel = ".SuperToPT"
  Desc = "one-to-one from super"
  [Base.Params]
    "Path.PathScale.Abs" = "0.5"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "3.0"

[[Base]]
  Sel = ".ACCToVMtx"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "1.5"
  [Base.Hypers]
    [Base.Hypers."Path.PathScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#VMtxNoToVMtxGo"
  Desc = ""
  [Base.Params]
    "Path.Learn.Learn" = "false"
    "Path.PathScale.Abs" = "1"
    "Path.PathScale.Rel" = "0.05"
  [Base.Hypers]
    [Base.Hypers."Path.PathScale.Rel"]
      Tweak = "log"

[[Base]]
  Sel = "#VGPi"
  Desc = ""
  [Base.Params]
    "Layer.Acts.Init.GeBase" = "0.3"
    "Layer.Acts.Init.GeVar" = "0.1"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Init.GeBase"]
      Tweak = "-"

[[Base]]
  Sel = "#VSTNToVGPi"
  Desc = "strong initial phasic activation"
  [Base.Params]
    "Path.PathScale.Abs" = ".2"
  [Base.Hypers]
    [Base.Hypers."Path.PathScale.Abs"]
      Tweak = "-"
