Name = 'RL'
Title = 'Reinforcement learning'
URL = 'https'
Doc = 'rl explores the temporal differences (TD) reinforcement learning algorithm under some basic Pavlovian conditioning environments.'
Includes = []
RW = false
GUI = false
Debug = false

[Env]

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = false
  GPUDevice = 0
  NData = 1
  NThreads = 0
  Run = 0
  Runs = 1
  Epochs = 100
  Trials = 20
  Cycles = 200
  PlusCycles = 50

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
