// Code generated by "goal build"; DO NOT EDIT.
//line act-net.goal:1
// Copyright (c) 2019, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package axon

import "cogentcore.org/core/enums"

// Cycle runs n cycles of activation updating.
// If getNeurons is true, then neuron state is synced back
// from the GPU (for cycle-level display etc). Otherwise only
// layer-level state is synced.
func (nt *Network) Cycle(ncyc int, getNeurons bool) {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	ld := int(nix.NLayers * ctx.NData)
	pd := int(nix.NPools * ctx.NData)

	ToGPUCtxGlobal() // this is not a significant speed factor
	for range ncyc {
		RunGatherSpikes(nd)
		RunLayerGi(ld)
		RunBetweenGi(ld)
		RunPoolGi(pd)
		RunCycleNeuron(nd)
		RunSendSpike(nd)
		RunCyclePost(ld)
		RunCycleInc(1)
	}

	if getNeurons {
		RunDoneLayersNeurons()
	}

	// todo: fix this:
	// var ldt, vta *Layer
	//
	//	for _, ly := range nt.Layers {
	//		if ly.Type == VTALayer {
	//			vta = ly
	//		} else if ly.Type == LDTLayer {
	//			ldt = ly
	//		} else {
	//			ly.CyclePost(ctx)
	//		}
	//	}
	//
	// // ordering of these is important
	//
	//	if ldt != nil {
	//		ldt.CyclePost(ctx)
	//	}
	//
	//	if vta != nil {
	//		vta.CyclePost(ctx)
	//	}
}

// NewState handles all initialization at start of new input pattern.
// This is called *before* applying external input data and operates across
// all data parallel values.  The current Context.NData should be set
// properly prior to calling this and subsequent Cycle methods.
func (nt *Network) NewState(mode enums.Enum, testing bool) {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	ctx.NewState(mode, testing)
	ToGPUCtxGlobal()
	RunNewStateLayer(int(nix.NLayers))
	RunNewStateNeuron(nd)
	RunInitGBuffsPath(int(nix.NPaths))
	// note: not completed until run cycles
}

// InitExt initializes external input state.
// Call prior to applying external inputs to layers.
func (nt *Network) InitExt() {
	// note: important to do this for GPU
	// to ensure partial inputs work the same way on CPU and GPU.
	for _, ly := range nt.Layers {
		if ly.Off {
			continue
		}
		ly.InitExt()
	}
}

// ApplyExts applies external inputs to layers, based on values
// that were set in prior layer-specific ApplyExt calls.
// This does nothing on the CPU, but is critical for the GPU,
// and should be added to all sims where GPU will be used.
func (nt *Network) ApplyExts() {
	if !UseGPU {
		return
	}
	ToGPU(ExtsVar)
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	RunApplyExtsNeuron(nd)
}

// Beta1 does updating at Beta1 timescale.
func (nt *Network) Beta1() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	RunBeta1Neuron(nd)
}

// Beta2 does updating at Beta1 timescale.
func (nt *Network) Beta2() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	RunBeta2Neuron(nd)
}

// MinusPhase does updating after end of minus phase.
func (nt *Network) MinusPhase() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	RunMinusPhasePool(int(nix.NPools))
	RunMinusPhaseNeuron(nd)
	RunMinusPhasePost(int(nix.NLayers))
}

// PlusPhaseStart does updating at the start of the plus phase:
// applies Target inputs as External inputs.
func (nt *Network) PlusPhaseStart() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)

	ctx.PlusPhaseStart()
	RunPlusPhaseStartNeuron(nd)
}

// PlusPhase does updating after end of plus phase.
// On GPU this is when we finally sync back Layers and Neurons.
func (nt *Network) PlusPhase() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	pd := int(nix.NPools * ctx.NData)
	RunPlusPhasePool(pd)
	RunPlusPhaseNeuron(nd)
	RunPlusPhasePost(int(nix.NLayers))
	RunDoneLayersNeurons()
}

// TargToExt sets external input Ext from target values Target
// This is done at end of MinusPhase to allow targets to drive activity in plus phase.
// This can be called separately to simulate alpha cycles within theta cycles, for example.
func (nt *Network) TargToExt() {
	ctx := nt.Context()
	for _, ly := range nt.Layers {
		if ly.Off {
			continue
		}
		ly.TargToExt(ctx)
	}
}

// ClearTargExt clears external inputs Ext that were set from target values Target.
// This can be called to simulate alpha cycles within theta cycles, for example.
func (nt *Network) ClearTargExt() {
	ctx := nt.Context()
	for _, ly := range nt.Layers {
		if ly.Off {
			continue
		}
		ly.ClearTargExt(ctx)
	}
}

// GPUTestWrite writes values to neuron, for testing
func (nt *Network) GPUTestWrite() {
	nix := nt.NetIxs()
	ctx := nt.Context()
	nd := int(nix.NNeurons * ctx.NData)
	RunGPUTestWrite(nd)
	RunDoneLayersNeurons()
}

//gosl:start

//////// Kernels for all parallel CPU / GPU compute are here:

// GatherSpikes is the kernel over Neurons * Data for gathering
// spike inputs sent on the previous cycle.
func GatherSpikes(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].GatherSpikes(ctx, ni, di)
}

// LayerGi is the kernel over Layers * Data for updating Gi inhibition.
func LayerGi(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	li := ctx.ItemIndex(i)
	Layers[li].LayerGi(ctx, li, di)
}

// BetweenGi is the kernel over Layers * Data for updating Gi
// inhibition between layers.
func BetweenGi(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	li := ctx.ItemIndex(i)
	Layers[li].BetweenGi(ctx, di)
}

// PoolGi is the kernel over Pools * Data for updating Gi inhibition.
func PoolGi(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	pi := ctx.ItemIndex(i)
	PoolPoolGi(ctx, pi, di)
}

// CycleNeuron is the kernel over Neurons * Data to do
// one cycle (msec) of updating at the neuron level.
func CycleNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].CycleNeuron(ctx, ni, di)
}

// SendSpike is the kernel over Neurons * Data to
// send spike signal for neurons over threshold.
func SendSpike(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].SendSpike(ctx, ni, di)
}

// CyclePost is the kernel over Layers * Data to
// update state after each Cycle of updating.
func CyclePost(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	li := ctx.ItemIndex(i)
	Layers[li].CyclePost(ctx, di)
}

// CycleInc is the kernel over 1 call to increment the cycle counter.
func CycleInc(i uint32) { //gosl:kernel
	if i != 0 {
		return
	}
	ctx := GetCtx(0)
	ctx.CycleInc()
}

// ApplyExtsNeuron is the kernel over Neurons * Data to
// apply Ext external input to the neurons receiving inputs.
func ApplyExtsNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].ApplyExtsNeuron(ni, di)
}

// NewStateLayer is the kernel over Layers (not Data)
// which does new state on pools as well.
func NewStateLayer(li uint32) { //gosl:kernel
	ctx := GetCtx(0)
	Layers[li].NewStateLayer(ctx)
}

// NewStateNeuron is the kernel over Neurons * Data to
// do new state on neurons (decay).
func NewStateNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].NewStateNeuron(ctx, ni, di)
}

// InitGBuffsPath is the kernel over Paths to
// initialize PathGBuf, PathGSyns.
func InitGBuffsPath(pti uint32) { //gosl:kernel
	ctx := GetCtx(0)
	Paths[pti].InitGBuffs(ctx)
}

// Beta1Neuron is the kernel over Neurons * Data to
// do neuron-level updating at Beta1.
func Beta1Neuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].Beta1Neuron(ctx, ni, di)
}

// Beta2Neuron is the kernel over Neurons * Data to
// do neuron-level updating at Beta1.
func Beta2Neuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].Beta2Neuron(ctx, ni, di)
}

////////  Minus Phase

// MinusPhasePool is the kernel over Pools to
// do pool-level updating after end of minus phase.
func MinusPhasePool(pi uint32) { //gosl:kernel
	ctx := GetCtx(0)
	li := PoolIxs.Value(int(pi), int(PoolLayerIdx))
	Layers[li].MinusPhasePool(ctx, pi)
}

// MinusPhaseNeuron is the kernel over Neurons * Data to
// do neuron-level updating after end of minus phase.
func MinusPhaseNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].MinusPhaseNeuron(ctx, ni, di)
}

// MinusPhasePost does special algorithm post processing.
func MinusPhasePost(li uint32) { //gosl:kernel
	ctx := GetCtx(0)
	Layers[li].MinusPhasePost(ctx)
}

// PlusPhaseStartNeuron is the kernel over Neurons * Data to
// do neuron-level updating at start of plus phase.
func PlusPhaseStartNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].PlusPhaseStartNeuron(ctx, ni, di)
}

// PlusPhasePool is the kernel over Pools * Data to
// do pool-level updating after end of plus phase.
func PlusPhasePool(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	pi := ctx.ItemIndex(i)
	li := PoolIxs.Value(int(pi), int(PoolLayerIdx))
	Layers[li].PlusPhasePool(ctx, pi, di)
}

// PlusPhaseNeuron is the kernel over Neurons * Data to
// do neuron-level updating after end of plus phase.
func PlusPhaseNeuron(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	li := NeuronIxs.Value(int(ni), int(NrnLayIndex))
	Layers[li].PlusPhaseNeuron(ctx, ni, di)
}

// PlusPhasePost does special algorithm post processing.
func PlusPhasePost(li uint32) { //gosl:kernel
	ctx := GetCtx(0)
	Layers[li].PlusPhasePost(ctx)
}

// GPUTestWrite is the kernel over Neurons * Data for testing
// the unique writing of data on GPU.
func GPUTestWrite(i uint32) { //gosl:kernel
	ctx := GetCtx(0)
	di := ctx.DataIndex(i)
	ni := ctx.ItemIndex(i)
	for vi := Spike; vi < NeuronVarsN; vi++ {
		Neurons.Set(float32(ni*1000+uint32(vi)), int(ni), int(di), int(vi))
	}
}

//gosl:end
