// Code generated by "stringer -type=DAModTypes"; DO NOT EDIT.

package axon

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDAMod-0]
	_ = x[D1Mod-1]
	_ = x[D2Mod-2]
	_ = x[D1AbsMod-3]
	_ = x[DAModTypesN-4]
}

const _DAModTypes_name = "NoDAModD1ModD2ModD1AbsModDAModTypesN"

var _DAModTypes_index = [...]uint8{0, 7, 12, 17, 25, 36}

func (i DAModTypes) String() string {
	if i < 0 || i >= DAModTypes(len(_DAModTypes_index)-1) {
		return "DAModTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DAModTypes_name[_DAModTypes_index[i]:_DAModTypes_index[i+1]]
}

func (i *DAModTypes) FromString(s string) error {
	for j := 0; j < len(_DAModTypes_index)-1; j++ {
		if s == _DAModTypes_name[_DAModTypes_index[j]:_DAModTypes_index[j+1]] {
			*i = DAModTypes(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: DAModTypes")
}
