// Code generated by "stringer -type=NeuronFlags"; DO NOT EDIT.

package axon

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NeuronOff-1]
	_ = x[NeuronHasExt-4]
	_ = x[NeuronHasTarg-8]
	_ = x[NeuronHasCmpr-16]
}

const (
	_NeuronFlags_name_0 = "NeuronOff"
	_NeuronFlags_name_1 = "NeuronHasExt"
	_NeuronFlags_name_2 = "NeuronHasTarg"
	_NeuronFlags_name_3 = "NeuronHasCmpr"
)

func (i NeuronFlags) String() string {
	switch {
	case i == 1:
		return _NeuronFlags_name_0
	case i == 4:
		return _NeuronFlags_name_1
	case i == 8:
		return _NeuronFlags_name_2
	case i == 16:
		return _NeuronFlags_name_3
	default:
		return "NeuronFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
