// Code generated by "stringer -type=SigDerivVars"; DO NOT EDIT.

package axon

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SigDerivM-0]
	_ = x[SigDerivP-1]
	_ = x[SigDerivD-2]
	_ = x[SigDerivVarsN-3]
}

const _SigDerivVars_name = "SigDerivMSigDerivPSigDerivDSigDerivVarsN"

var _SigDerivVars_index = [...]uint8{0, 9, 18, 27, 40}

func (i SigDerivVars) String() string {
	if i < 0 || i >= SigDerivVars(len(_SigDerivVars_index)-1) {
		return "SigDerivVars(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SigDerivVars_name[_SigDerivVars_index[i]:_SigDerivVars_index[i+1]]
}

func (i *SigDerivVars) FromString(s string) error {
	for j := 0; j < len(_SigDerivVars_index)-1; j++ {
		if s == _SigDerivVars_name[_SigDerivVars_index[j]:_SigDerivVars_index[j+1]] {
			*i = SigDerivVars(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: SigDerivVars")
}
