// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package axon

const (
	Version     = "v1.2.4"
	GitCommit   = "5ff6035" // the commit JUST BEFORE the release
	VersionDate = "2021-04-20 08:05" // UTC
)

