// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package axon

const (
	Version     = "v1.8.2"
	GitCommit   = "0a7322c"          // the commit JUST BEFORE the release
	VersionDate = "2023-06-28 08:31" // UTC
)
