// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package axon

const (
	Version     = "v1.2.22"
	GitCommit   = "e9bab3b" // the commit JUST BEFORE the release
	VersionDate = "2021-05-06 09:29" // UTC
)

