Name = 'DeepMusic'
Title = 'DeepAxon Music Prediction'
URL = 'https'
Doc = 'This demonstrates a basic deep predictive learning Axon model that learns to predict the next note in a song.'
Includes = [
  'fullsong.toml'
]
GUI = false
Debug = false

[Env]
  UnitsPer = 4
  FullSong = true
  PlayTarg = false
  TestClamp = true

[Params]
  Hid2 = false
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 500
  Trials = 768
  Cycles = 200
  PlusCycles = 50
  TestInterval = 0
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
