Name = 'DeepMusic'
Title = 'DeepAxon Music Prediction'
URL = 'https://github.com/emer/axon/blob/main/sims/deepmusic/README.md'
Doc = 'This demonstrates a basic deep predictive learning Axon model that learns to predict the next note in a song.'
Includes = [
  'fullsong.toml'
]
GUI = false
Debug = false
GPU = true

[Env]
  UnitsPer = 4
  FullSong = true
  PlayTarg = false
  TestClamp = true

[Params]
  Hid2 = true
  NUnitsY = 15
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 10
  Epochs = 500
  Trials = 768
  Cycles = 200
  PlusCycles = 50
  NZero = 2
  TestInterval = 0
  PCAInterval = 0
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Expt',
    'Run',
    'Epoch'
  ]
  Test = []
