[[Base]]
  Sel = "Layer"
  Desc = "generic params for all layers: lower gain, slower, soft clamp"
  [Base.Params]
    "Layer.Acts.Decay.Act" = "0.0"
    "Layer.Acts.Decay.Glong" = "0.0"
    "Layer.Acts.Dt.GeTau" = "5"
    "Layer.Acts.Dt.GiTau" = "7"
    "Layer.Acts.Gbar.I" = "1.0"
    "Layer.Acts.Gbar.L" = "0.2"
    "Layer.Acts.Noise.Ge" = "0.002"
    "Layer.Acts.Noise.GeHz" = "100"
    "Layer.Acts.Noise.Gi" = "0.002"
    "Layer.Acts.Noise.GiHz" = "200"
    "Layer.Acts.Noise.On" = "false"
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Inhib.Layer.Gi" = "1.0"
    "Layer.Inhib.Layer.On" = "false"

[[Base]]
  Sel = ".InhibLay"
  Desc = "generic params for all layers: lower gain, slower, soft clamp"
  [Base.Params]
    "Layer.Acts.Erev.L" = "0.4"
    "Layer.Acts.GabaB.Gbar" = "0"
    "Layer.Acts.Gbar.L" = "0.2"
    "Layer.Acts.Init.Vm" = "0.4"
    "Layer.Acts.KNa.On" = "false"
    "Layer.Acts.NMDA.Gbar" = "0"
    "Layer.Acts.Noise.Ge" = "0.01"
    "Layer.Acts.Noise.Gi" = "0.0"
    "Layer.Acts.Noise.On" = "false"
    "Layer.Acts.Spikes.Thr" = "0.5"
    "Layer.Acts.Spikes.Tr" = "1"
    "Layer.Acts.Spikes.VmR" = "0.4"
    "Layer.Inhib.ActAvg.Nominal" = "0.5"

[[Base]]
  Sel = "#Layer0"
  Desc = "Input layer"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "0.6"
    "Layer.Acts.Noise.Gi" = "0.002"
    "Layer.Acts.Noise.On" = "true"

[[Base]]
  Sel = "Path"
  Desc = "no learning"
  [Base.Params]
    "Path.Com.Delay" = "2"
    "Path.Learn.Learn" = "false"
    "Path.SWts.Init.Mean" = "0.5"
    "Path.SWts.Init.Var" = "0.25"

[[Base]]
  Sel = ".BackPath"
  Desc = "feedback excitatory"
  [Base.Params]
    "Path.PathScale.Rel" = "0.2"

[[Base]]
  Sel = ".InhibPath"
  Desc = "inhibitory pathways"
  [Base.Params]
    "Path.Com.Delay" = "0"
    "Path.PathScale.Abs" = "6"
    "Path.SWts.Init.Mean" = "0.5"
    "Path.SWts.Init.Sym" = "false"
    "Path.SWts.Init.Var" = "0"

[[Base]]
  Sel = ".ToInhib"
  Desc = "to inhibitory pathways"
  [Base.Params]
    "Path.Com.Delay" = "1"

[[FSFFFB]]
  Sel = "Layer"
  Desc = "use FSFFFB computed inhibition"
  [FSFFFB.Params]
    "Layer.Inhib.Layer.FB" = "1"
    "Layer.Inhib.Layer.FS0" = "0.1"
    "Layer.Inhib.Layer.FSTau" = "6"
    "Layer.Inhib.Layer.Gi" = "1.0"
    "Layer.Inhib.Layer.On" = "true"
    "Layer.Inhib.Layer.SS" = "30"
    "Layer.Inhib.Layer.SSfTau" = "20"
    "Layer.Inhib.Layer.SSiTau" = "50"

[[FSFFFB]]
  Sel = ".InhibPath"
  Desc = "inhibitory pathways"
  [FSFFFB.Params]
    "Path.PathScale.Abs" = "0"

[[Trained]]
  Sel = ".Excite"
  Desc = "excitatory connections"
  [Trained.Params]
    "Path.SWts.Init.Mean" = "0.4"
    "Path.SWts.Init.Var" = "0.8"

[[Untrained]]
  Sel = ".Excite"
  Desc = "excitatory connections"
  [Untrained.Params]
    "Path.SWts.Init.Mean" = "0.5"
    "Path.SWts.Init.Var" = "0.25"
