// Code generated by "core generate -add-types -add-funcs -gosl"; DO NOT EDIT.

package consatenv

import (
	"cogentcore.org/core/enums"
)

var _RelationsValues = []Relations{0, 1, 2}

// RelationsN is the highest valid value for type Relations, plus one.
//
//gosl:start
const RelationsN Relations = 3

//gosl:end

var _RelationsValueMap = map[string]Relations{`Equal`: 0, `Greater`: 1, `Less`: 2}

var _RelationsDescMap = map[Relations]string{0: ``, 1: ``, 2: ``}

var _RelationsMap = map[Relations]string{0: `Equal`, 1: `Greater`, 2: `Less`}

// String returns the string representation of this Relations value.
func (i Relations) String() string { return enums.String(i, _RelationsMap) }

// SetString sets the Relations value from its string representation,
// and returns an error if the string is invalid.
func (i *Relations) SetString(s string) error {
	return enums.SetString(i, s, _RelationsValueMap, "Relations")
}

// Int64 returns the Relations value as an int64.
func (i Relations) Int64() int64 { return int64(i) }

// SetInt64 sets the Relations value from an int64.
func (i *Relations) SetInt64(in int64) { *i = Relations(in) }

// Desc returns the description of the Relations value.
func (i Relations) Desc() string { return enums.Desc(i, _RelationsDescMap) }

// RelationsValues returns all possible values for the type Relations.
func RelationsValues() []Relations { return _RelationsValues }

// Values returns all possible values for the type Relations.
func (i Relations) Values() []enums.Enum { return enums.Values(_RelationsValues) }

// MarshalText implements the [encoding.TextMarshaler] interface.
func (i Relations) MarshalText() ([]byte, error) { return []byte(i.String()), nil }

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
func (i *Relations) UnmarshalText(text []byte) error {
	return enums.UnmarshalText(i, text, "Relations")
}
