// Copyright (c) 2023, The Emergent Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cond

const (
	// DefTicks is the default number of ticks per block
	DefTicks = 7

	// DefCSTick is the default tick to present the CS
	DefCSTick = 1

	// DefUSTick is the default tick to present the US
	DefUSTick = 4
)

var AllBlocks = map[string]Block{
	"PosAcq_A100": {
		{
			Name:     "A_R",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosReAcq_A100": {
		{
			Name:     "A_R_re",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosAcq_A100B50": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0.5,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       1,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcq_A100B0": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_NR",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0.0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcq_A50": {
		{
			Name:     "A_R",
			Pct:      1.0,
			Valence:  Pos,
			USProb:   0.5,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"US0": {
		{
			Name:     "A_R",
			Pct:      1.0,
			Valence:  Pos,
			USProb:   0.01,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosReAcq_A100B50": {
		{
			Name:     "A_R_re",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R_re",
			Pct:      0,
			Valence:  Pos,
			USProb:   0.5,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcqPreSecondOrder": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks + 2,
			CS:       "A",
			CSStart:  3,
			CSEnd:    5,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  5,
			USEnd:    5,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0.5,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks + 2,
			CS:       "B",
			CSStart:  3,
			CSEnd:    5,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  5,
			USEnd:    5,
			Context:  "B",
		},
	},
	"PosAcq_A100B100": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcq_A100B25": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0.250,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcqOmit": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "A_NR",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosNeg": {
		{
			Name:     "Z_R",
			Pct:      0.167,
			Valence:  Neg,
			USProb:   0.250,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
		{
			Name:     "Z_R",
			Pct:      0.167,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
		{
			Name:     "Z_R_tst",
			Pct:      0.167,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
		{
			Name:     "W_R",
			Pct:      0.167,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "W",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "W",
		},
		{
			Name:     "W_R",
			Pct:      0.167,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "W",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "W",
		},
		{
			Name:     "W_R_test",
			Test:     true,
			Pct:      0.167,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "W",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "W",
		},
	},
	"PosOrNegAcq": {
		{
			Name:     "Z_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  true,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
		{
			Name:     "Z_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  true,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
	},
	"Overexpectation_train": {
		{
			Name:     "A_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
		{
			Name:     "C_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "X_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
		{
			Name:     "Y_NR",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "Y",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Y",
		},
	},
	"OverexpectationCompound": {
		{
			Name:     "AX_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "BY_NR",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "BY",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "BY",
		},
		{
			Name:     "CY_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "CY",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "CY",
		},
		{
			Name:     "X_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
		{
			Name:     "Y_NR",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "Y",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Y",
		},
	},
	"Overexpectation_test": {
		{
			Name:     "A_NR_test",
			Test:     true,
			Pct:      0.250,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_NR_test",
			Test:     true,
			Pct:      0.250,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
		{
			Name:     "C_NR_test",
			Test:     true,
			Pct:      0.250,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "X_R_test",
			Test:     true,
			Pct:      0.250,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
	},
	"PosAcqEarlyUS_test": {
		{
			Name:     "A_R_late",
			Test:     true,
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  4,
			USEnd:    4,
			Context:  "A",
		},
		{
			Name:     "A_R_early",
			Test:     true,
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  2,
			USEnd:    2,
			Context:  "A",
		},
	},
	"PosOrienting": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcqMagnitude": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosAcqMagnitudeChange": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"NegAcqMagnitude": {
		{
			Name:     "D_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
	},
	"NegAcqMagnitudeChange": {
		{
			Name:     "D_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
	},
	"PosExt_A0": {
		{
			Name:     "A_NR",
			Pct:      1,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosExt_A0B0": {
		{
			Name:     "A_NR",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_NR",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosCondInhib": {
		{
			Name:     "A_R",
			Pct:      0.650,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "AX_NR",
			Pct:      0.350,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
	},
	"PosCondInhib_test": {
		{
			Name:     "A_NR_test",
			Test:     true,
			Pct:      0.330,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "AX_NR_test",
			Test:     true,
			Pct:      0.330,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "X_NR_test",
			Test:     true,
			Pct:      0.330,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
	},
	"PosSecondOrderCond": {
		{
			Name:     "A_R",
			Pct:      0.950,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  true,
			USMag:    1,
			NTicks:   DefTicks + 2,
			CS:       "A",
			CSStart:  3,
			CSEnd:    5,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  5,
			USEnd:    5,
			Context:  "A",
		},
		{
			Name:     "AC_NR",
			Pct:      0.050,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks + 2,
			CS:       "AC",
			CSStart:  3,
			CSEnd:    5,
			CS2Start: 1,
			CS2End:   2,
			US:       0,
			USStart:  5,
			USEnd:    5,
			Context:  "AC",
		},
	},
	"NegAcq_D100": {
		{
			Name:     "D_R",
			Pct:      1,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
	},
	"NegExt_D0": {
		{
			Name:     "D_NR",
			Pct:      1,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
	},
	"NegAcq_D100E25": {
		{
			Name:     "D_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   0.250,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
	},
	"NegExt_D0E0": {
		{
			Name:     "D_NR",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   0.5,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
	},
	"NegCondInhib": {
		{
			Name:     "D_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "DU_NR",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "DU",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "DU",
		},
	},
	"NegCondInhib_test": {
		{
			Name:     "D_NR_test",
			Test:     true,
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "DU_NR_test",
			Test:     true,
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "DU",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "DU",
		},
		{
			Name:     "U_NR_test",
			Test:     true,
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "U",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "U",
		},
	},
	"PosAcq_cxA": {
		{
			Name:     "A_R_cxA",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosExtinct_cxB": {
		{
			Name:     "A_NR_cxB",
			Pct:      1,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A_B",
		},
	},
	"PosRenewal_cxA": {
		{
			Name:     "A_NR_cxA",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "A_NR_cxB",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A_B",
		},
	},
	"PosBlocking_A_train": {
		{
			Name:     "A_R",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosBlocking": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "AB_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AB",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AB",
		},
	},
	"PosBlocking_test": {
		{
			Name:     "B_R_test",
			Test:     true,
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"PosBlocking2_test": {
		{
			Name:     "A_R_test",
			Test:     true,
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R_test",
			Test:     true,
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"NegBlocking_E_train": {
		{
			Name:     "E_R",
			Pct:      1,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
	},
	"NegBlocking": {
		{
			Name:     "E_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
		{
			Name:     "ED_R",
			Pct:      0.5,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "ED",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "ED",
		},
	},
	"NegBlocking_test": {
		{
			Name:     "D_R",
			Test:     true,
			Pct:      1,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
	},
	"PosSumAcq": {
		{
			Name:     "A_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "B_NR",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"NegSumAcq": {
		{
			Name:     "D_R",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_R",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
		{
			Name:     "F_NR",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "F",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "F",
		},
	},
	"PosCondInhib_BY": {
		{
			Name:     "A_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "AX_NR",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "BY_NR",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "BY",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "BY",
		},
	},
	"NegCondInhib_FV": {
		{
			Name:     "D_R",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "DU_NR",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "DU",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "DU",
		},
		{
			Name:     "FV_NR",
			Pct:      0.333,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    0,
			NTicks:   DefTicks,
			CS:       "FV",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "FV",
		},
	},
	"NegSumCondInhib_test": {
		{
			Name:     "D_NR_test",
			Test:     true,
			Pct:      0.171,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "D",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "D",
		},
		{
			Name:     "E_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "E",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "E",
		},
		{
			Name:     "U_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "U",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "U",
		},
		{
			Name:     "DU_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "DU",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "DU",
		},
		{
			Name:     "EU_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "EU",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "EU",
		},
		{
			Name:     "EV_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Neg,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "EV",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "EV",
		},
	},
	"PosSumCondInhib_test": {
		{
			Name:     "A_NR_test",
			Test:     true,
			Pct:      0.171,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "X_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
		{
			Name:     "AX_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "CX_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "CX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "CX",
		},
		{
			Name:     "CY_NR_test",
			Test:     true,
			Pct:      0.166,
			Valence:  Pos,
			USProb:   0,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "CY",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "CY",
		},
	},
	"Unblocking_train": {
		{
			Name:     "A_R",
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_R",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "B_R",
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"UnblockingValue": {
		{
			Name:     "AX_R",
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "CZ_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "CZ",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "CZ",
		},
		{
			Name:     "A_R",
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "B_R",
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"UnblockingValue_test": {
		{
			Name:     "A_R_test",
			Test:     true,
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_R_test",
			Test:     true,
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "X_R_test",
			Test:     true,
			Pct:      0,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
		{
			Name:     "Z_R_test",
			Test:     true,
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Z",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Z",
		},
	},
	"Unblocking_trainUS": {
		{
			Name:     "A_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "C_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.100,
			NTicks:   DefTicks,
			CS:       "C",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "C",
		},
		{
			Name:     "B_R",
			Pct:      0.333,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       1,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"UnblockingIdentity": {
		{
			Name:     "AX_R",
			Pct:      0.300,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AX",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AX",
		},
		{
			Name:     "BY_R",
			Pct:      0.300,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "BY",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "BY",
		},
		{
			Name:     "A_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R",
			Pct:      0.200,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       1,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"UnblockingIdentity_test": {
		{
			Name:     "A_R_test",
			Test:     true,
			Pct:      0.251,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "B_R_test",
			Test:     true,
			Pct:      0.251,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       1,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
		{
			Name:     "X_R_test",
			Test:     true,
			Pct:      0.251,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "X",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "X",
		},
		{
			Name:     "Y_R_test",
			Test:     true,
			Pct:      0.248,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "Y",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "Y",
		},
	},
	"PosUpUnblocking_A_train": {
		{
			Name:     "A_R",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
	"PosUpUnblocking": {
		{
			Name:     "A_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    0.5,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
		{
			Name:     "AB_R",
			Pct:      0.5,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "AB",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: 1,
			CS2End:   3,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "AB",
		},
	},
	"PosUpUnblocking_test": {
		{
			Name:     "B_R",
			Test:     true,
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "B",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "B",
		},
	},
	"BlankTemplate": {
		{
			Name:     "",
			Pct:      1,
			Valence:  Pos,
			USProb:   1,
			MixedUS:  false,
			USMag:    1,
			NTicks:   DefTicks,
			CS:       "A",
			CSStart:  DefCSTick,
			CSEnd:    DefUSTick,
			CS2Start: -1,
			CS2End:   -1,
			US:       0,
			USStart:  DefUSTick,
			USEnd:    DefUSTick,
			Context:  "A",
		},
	},
}
