Name = 'DeepFSA'
Title = 'DeepAxon Finite State Automaton'
URL = 'https'
Doc = 'This demonstrates a basic deep predictive learning Axon model on the Finite State Automaton problem (e.g.'
Includes = []
GUI = false
Debug = false

[Env]
  UnitsPer = 1
  InputNames = [
    'B',
    'T',
    'S',
    'X',
    'V',
    'P',
    'E'
  ]

  [Env.InputNameMap]
    B = 0
    E = 6
    P = 5
    S = 2
    T = 1
    V = 4
    X = 3

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 200
  Trials = 196
  Cycles = 200
  PlusCycles = 50
  NZero = 2
  TestInterval = 0
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
