Name = 'FSA'
Title = 'Finite State Automaton'
URL = 'https://github.com/emer/axon/blob/main/sims/deepfsa/README.md'
Doc = 'This demonstrates a basic deep predictive learning Axon model on the Finite State Automaton problem (e.g., the Reber grammar). The network learns the underlying grammar that generates partially ambiguous observable state tokens, strictly through errors in predicting the sequences of these tokens.'
Includes = []
GUI = false
Debug = false
GPU = true

[Env]
  UnitsPer = 1
  InputNames = [
    'B',
    'T',
    'S',
    'X',
    'V',
    'P',
    'E'
  ]

  [Env.InputNameMap]
    B = 0
    E = 6
    P = 5
    S = 2
    T = 1
    V = 4
    X = 3

[Params]
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPUDevice = 0
  NData = 16
  NThreads = 0
  Run = 0
  Runs = 5
  Epochs = 200
  Trials = 196
  Cycles = 200
  PlusCycles = 50
  NZero = 2
  TestInterval = 0
  PCAInterval = 10
  StartWeights = ''

[Log]
  SaveWeights = false
  Train = [
    'Expt',
    'Run',
    'Epoch'
  ]
  Test = []
