Includes = []
GUI = false
Debug = false

[Env]
  [Env.Env]
    NItems = 10
    NTrials = 10

[Params]
  MaintCons = false
  NUnits = 7
  Tweak = false
  Baseline = false
  DryRun = false
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = false
  NData = 1
  NThreads = 0
  Run = 0
  NRuns = 1
  NEpochs = 10
  NTrials = 64

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
  Testing = false
