Name = 'PFCMaintS'
Title = 'Prefrontal Cortex Maintenance'
URL = 'https'
Doc = 'This project tests prefrontal cortex (PFC) active maintenance mechanisms supported by the pyramidal tract (PT) neurons'
Includes = []
GUI = false
Debug = false

[Env]
  [Env.Env]
    NItems = 8
    NTrials = 8

[Params]
  MaintCons = false
  NUnits = 7
  Tweak = false
  Baseline = false
  DryRun = false
  Script = ''
  Sheet = ''
  Tag = ''
  Note = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  GPUDevice = 0
  NData = 8
  NThreads = 0
  Run = 0
  Runs = 1
  Epochs = 50
  Trials = 128
  Cycles = 200
  PlusCycles = 50

[Log]
  SaveWeights = false
  Train = [
    'Run',
    'Epoch'
  ]
  Test = []
